import type { JsonValue } from "@/lib/server/types";

export const ITEM_COMPONENTS = [
  "custom_data",
  "damage",
  "repair_cost",
  "unbreakable",
  "enchantments",
  "stored_enchantments",
  "custom_name",
  "lore",
  "can_break",
  "can_place_on",
  "dyed_color",
  "attribute_modifiers",
  "charged_projectiles",
  "intangible_projectile",
  "bundle_contents",
  "map_color",
  "map_decorations",
  "map_id",
  "custom_model_data",
  "potion_contents",
  "potion_duration_scale",
  "writable_book_content",
  "written_book_content",
  "trim",
  "suspicious_stew",
  "debug_stick_state",
  "entity_data",
  "bucket_entity_data",
  "instrument",
  "recipes",
  "lodestone_tracker",
  "firework_explosion",
  "fireworks",
  "profile",
  "note_block_sound",
  "base_color",
  "banner_patterns",
  "pot_decorations",
  "container",
  "bees",
  "lock",
  "container_loot",
  "block_entity_data",
  "block_state",
  "enchantment_glint_override",
  "food",
  "max_stack_size",
  "max_damage",
  "tool",
  "item_name",
  "damage_resistant",
  "rarity",
  "ominous_bottle_amplifier",
  "jukebox_playable",
  "consumable",
  "use_remainder",
  "use_cooldown",
  "item_model",
  "equippable",
  "glider",
  "tooltip_style",
  "death_protection",
  "repairable",
  "enchantable"
] as const;

export const DEFAULT_COMPONENT_VALUES: Record<string, JsonValue> = {
  custom_data: {},
  damage: 0,
  repair_cost: 0,
  unbreakable: {},
  enchantments: {},
  stored_enchantments: {},
  custom_name: { text: "Custom Name" },
  lore: [{ text: "Lore" }],
  can_break: { blocks: "minecraft:stone" },
  can_place_on: { blocks: "minecraft:stone" },
  dyed_color: 16777215,
  attribute_modifiers: [],
  charged_projectiles: [{ id: "minecraft:arrow" }],
  intangible_projectile: {},
  bundle_contents: [],
  map_color: 4603950,
  map_decorations: {},
  map_id: 0,
  custom_model_data: { floats: [9075] },
  potion_contents: { potion: "minecraft:water" },
  potion_duration_scale: 1,
  writable_book_content: { pages: [] },
  written_book_content: { title: "Title", author: "Author", pages: [] },
  trim: { pattern: "minecraft:sentry", material: "minecraft:iron" },
  suspicious_stew: [],
  debug_stick_state: {},
  entity_data: { id: "minecraft:pig" },
  bucket_entity_data: {},
  instrument: "minecraft:ponder_goat_horn",
  recipes: [],
  lodestone_tracker: { target: { dimension: "minecraft:overworld", pos: [0, 64, 0] }, tracked: true },
  firework_explosion: { shape: "small_ball", colors: [] },
  fireworks: { flight_duration: 1, explosions: [] },
  profile: { name: "Player" },
  note_block_sound: "minecraft:block.note_block.harp",
  base_color: "white",
  banner_patterns: [],
  pot_decorations: [],
  container: [],
  bees: [],
  lock: "key",
  container_loot: { loot_table: "minecraft:empty" },
  block_entity_data: {},
  block_state: {},
  enchantment_glint_override: true,
  food: { nutrition: 1, saturation_modifier: 0.1 },
  max_stack_size: 64,
  max_damage: 100,
  tool: { rules: [] },
  item_name: { text: "Item Name" },
  damage_resistant: { types: "#minecraft:is_fire" },
  rarity: "common",
  ominous_bottle_amplifier: 0,
  jukebox_playable: "minecraft:precipice",
  consumable: {
    consume_seconds: 1.6,
    animation: "eat",
    sound: "minecraft:entity.generic.eat",
    has_consume_particles: true
  },
  use_remainder: { id: "minecraft:glass_bottle", count: 1 },
  use_cooldown: { seconds: 1 },
  item_model: "minecraft:paper",
  equippable: { slot: "head" },
  glider: {},
  tooltip_style: "minecraft:default",
  death_protection: {},
  repairable: { items: "minecraft:iron_ingot" },
  enchantable: { value: 15 }
};
